### ISSUE TITLE
Suggestions and questions about the flask back-end

### ISSUE THREAD

**Issue by 99Kies** [SUIBE-Blockchain/FISCO-BCOS-Toolbox#2]
hey! It's Good Idea. 
Actually, I also had the idea of integrating a separate Flask Web version of FISCO BCOS.
Flask is really easy to develop. 
This is my suggestion:
1. Improve the **/login** page (or is it already in the next version?)
2. Add **manager.py**(import flask_script)
3. Some areas of the code need to be optimized(Like **protecting the view**)
4. ......

I'm sorry because I haven't run it yet, so that's the limit.
This is just a suggestion in the back-end direction. [ I am not an expert in blockchain. ]

**Comment by leeduckgo** [comment]
> hey! It's Good Idea.
> Actually, I also had the idea of integrating a separate Flask Web version of FISCO BCOS.
> Flask is really easy to develop.
> This is my suggestion:
> 
> 1. Improve the **/login** page (or is it already in the next version?)
> 2. Add **manager.py**(import flask_script)
> 3. Some areas of the code need to be optimized(Like **protecting the view**)
> 4. ......
> 
> I'm sorry because I haven't run it yet, so that's the limit.
> This is just a suggestion in the back-end direction. [ I am not an expert in blockchain. ]

Thx.
1. **/login** page is on Schedule:)
2. flask db init, migrate and upgrade is supported yet.
3. Yes, there are a lot of things need to do......And we're making a Github-Project in these days.

U can contact me with wechat: 197626581

**Comment by 99Kies** [comment]
got it!
