### ISSUE TITLE
初始化数据库报错 唯一主键冲突

### ISSUE THREAD

**Issue by xiaoyue2019** [SUIBE-Blockchain/FISCO-BCOS-Toolbox#24]
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: users.email
[SQL: INSERT INTO users (username, email, password, created_at, first_name, last_name, active, is_admin) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('admin', 'admin@admin.com', <memory at 0x0000028CF585B708>, '2020-07-06 08:36:08.060930', None, None, 1, 1)]
(Background on this error at: http://sqlalche.me/e/gkpj)

加个判断或者删库操作

汤师傅加油

**Comment by xiaoyue2019** [comment]
汤师傅 tql ！！！！

**Comment by leeduckgo** [comment]
把解决方案附上………………

**Comment by xiaoyue2019** [comment]
因为db_init生成时已经存在test.db，删除fisco_bcos_toolbox下的test.db就行了。

——————
上海对外经贸大学区块链技术与应用研究中心
