### ISSUE TITLE
DEMO演示地址访问不了

### ISSUE THREAD

**Issue by susengo** [SUIBE-Blockchain/FISCO-BCOS-Toolbox#43]
DEMO: https://tools.doge.university/，无法访问，提示504错误

**Comment by leeduckgo** [comment]
收到，我们更新一下

**Comment by leeduckgo** [comment]
> DEMO: [https://tools.doge.university/，无法访问，提示504错误](https://tools.doge.university/%EF%BC%8C%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%EF%BC%8C%E6%8F%90%E7%A4%BA504%E9%94%99%E8%AF%AF)

恢复了，谢谢提交Issue~

**Comment by leeduckgo** [comment]
> DEMO: [https://tools.doge.university/，无法访问，提示504错误](https://tools.doge.university/%EF%BC%8C%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%EF%BC%8C%E6%8F%90%E7%A4%BA504%E9%94%99%E8%AF%AF)

可以加个v信：197626581

**Comment by leeduckgo** [comment]
发现服务有时候会挂掉，加了gunicorn……
` gunicorn -w 4 -b 127.0.0.1:5000 autoapp:app`
似乎还可以进一步加上Supervisor
> https://www.jianshu.com/p/7b85acb7b90d
