### ISSUE TITLE
SDK 配置通过WEB页面配置并提供下载

### ISSUE THREAD

**Issue by leeduckgo** [SUIBE-Blockchain/FISCO-BCOS-Toolbox#7]
SDK 配置通过WEB页面配置并提供下载

**Comment by 99Kies** [comment]
部署调用合约的功能实现不难。
但是需要以什么形式实现呢？
1. 一台服务器搭建主服务，active用户全在这台服务上部署合约
2. 一台服务器搭建主服务，给每个active标签用户分配一个docker容器，用于部署合约，互不影响。

**Comment by xiaoyue2019** [comment]
> 部署部署合约的功能实现不难。
> 但是需要以什么形式实现呢？
> 
> 1. 一台服务器搭建主服务，active用户全在这台服务上部署合约
> 2. 一台服务器搭建主服务，给每个活动标签用户分配一个docker容器，用于部署合约，互不影响。

前排吃瓜之我选1

**Comment by xiaoyue2019** [comment]
> 部署部署合约的功能实现不难。
> 但是需要以什么形式实现呢？
> 
> 1. 一台服务器搭建主服务，active用户全在这台服务上部署合约
> 2. 一台服务器搭建主服务，给每个活动标签用户分配一个docker容器，用于部署合约，互不影响。

前排吃瓜之我选1

**Comment by leeduckgo** [comment]
> 部署调用合约的功能实现不难。
> 但是需要以什么形式实现呢？
> 
> 1. 一台服务器搭建主服务，active用户全在这台服务上部署合约
> 2. 一台服务器搭建主服务，给每个active标签用户分配一个docker容器，用于部署合约，互不影响。

1 — 这个比较简单。
